services:
  nestjs:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    command: sh -c "npm run migration:run && npm run start:dev"
    environment:
      - NODE_ENV=production
  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

