services:
  postgres:
    image: postgres:16
    container_name: kolyaspeakingwordbot-postgres
    restart: always
    environment:
      POSTGRES_DB: kolyaspeakingwordbot
      POSTGRES_USER: kolya
      POSTGRES_PASSWORD: kolya_pass
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
