services:
  postgres:
    image: postgres:16
    container_name: kolyaspeakingwordbot-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nestjs:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh", "./wait-for-it.sh", "postgres", "5432", "sh", "-c", "npx prisma migrate deploy && pnpm run start:dev"]
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://kolya:kolya_pass@postgres/kolyaspeakingwordbot
  
      
volumes:
  postgres_data:
