services:
  postgres:
    image: postgres:16
    container_name: kolyaspeakingwordbot-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5444:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  nestjs:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - .:/app_source:ro
    ports:
      - "3030:3000"
    command: sh after_start_nest.sh
  admin:
    image: node:20-alpine
    volumes:
      - .:/app_source:ro
    working_dir: /app_source
    command: sh after_start_admin.sh
    ports:
      - "3031:3001"
  redis:
    image: redis:7-alpine
    container_name: kolyaspeakingwordbot-redis
    restart: always
    ports:
      - "6379:6379"

