services:
  postgres:
    image: postgres:16
    container_name: kolyaspeakingwordbot-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: kolyaspeakingwordbot-redis
    restart: always
    ports:
      - "6379:6379"
  
      
volumes:
  postgres_data:
