services:
  nestjs:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - .:/app_source:ro
    ports:
      - "3030:3000"
    command: sh after_start_nest.sh
  admin:
    image: node:20-alpine
    volumes:
      - .:/app_source:ro
    working_dir: /app_source
    command: sh after_start_admin.sh
    ports:
      - "3031:3001"

